### ISSUE TITLE
AJUDA

### ISSUE THREAD

**Issue by migueltarga** [caiqueff/Peko#1]
Tenho vergonha de fork esse projeto, e aparecer no meu github, mas queria ajudar.
Como faco?

**Comment by rscafi** [comment]
Agora já era, já sujou seu nome, cara
![image](https://cloud.githubusercontent.com/assets/6104262/18483851/57c1ac58-79bc-11e6-84b9-d433233323f9.png)

**Comment by migueltarga** [comment]
Merda! Vou contactar o github.

**Comment by caiqueff** [comment]
Só pode ajudar quem é da PPN. sorry

**Comment by migueltarga** [comment]
ok, obrigado
